#!/bin/bash

year="15"
season="2015"

scrapy crawl skatsum -a season="${season}"
echo "skatsum${year}"
scrapy crawl skatbio -a season="${season}"
echo "skatbio${year}"
scrapy crawl skateng -a season="${season}"
echo "skateng${year}"
scrapy crawl skatpim -a season="${season}"
echo "skatpim${year}"
scrapy crawl skatpm -a season="${season}"
echo "skatpm${year}"
scrapy crawl skatrts -a season="${season}"
echo "skatrts${year}"
scrapy crawl skatso -a season="${season}"
echo "skatso${year}"
scrapy crawl skatot -a season="${season}"
echo "skatot${year}"
scrapy crawl skattoi -a season="${season}"
echo "skattoi${year}"